In [13]:
#import os
#os.listdir()
from city import *

GEO_DEFINITIONS = {
    'phi': [{'county': 'Philadelphia', 'state': 'Pennsylvania'}],
    'chi': [{'county': 'Cook', 'state': 'Illinois'}],
    'sf': [{'county': 'San Francisco','state': 'California'}], 
    'sfba': [{'county': 'San Francisco','state': 'California'}, {'county': 'Contra Costa','state': 'California'}, 
            {'county': 'Alameda','state': 'California'}, {'county': 'San Mateo', 'state': 'California'},
            {'county': 'Santa Clara', 'state': 'California'}],
    'eastbay': [{'county': 'Contra Costa','state': 'California'}, {'county': 'Alameda','state': 'California'}],
    'nyc': [{'county': 'King', 'state': 'New York'}, {'county': 'Queens', 'state': 'New York'}, 
            {'county': 'New York', 'state': 'New York'}, {'county': 'Bronx', 'state': 'New York'}]
}

INFRA_TYPES = {
    'bridge': {'bridge':['yes','viaduct']},
    'highway': {'highway': ['motorway','motorway_link','motorway_junctions']},
    'coastline': {'natural':'coastline'},
    'water': {'natural':'water'}
}

INFRA_TYPES_2 = {
#    'bridge': {'bridge':['yes','viaduct']},
    'highway': {'highway': ['motorway','motorway_link','motorway_junctions']}#,
##   'coastline': {'natural':'coastline'},
#    'water': {'natural':'water'}
}

In [ ]:
# Create City
c_phi = City('Philadelphia',GEO_DEFINITIONS['phi'], '../data/replica_exports/replica-phi_sat_spring_2024-01_14_25-trips_dataset.csv')

# Add Infrastructure
c_phi.load_infrastructure(INFRA_TYPES)

# Split
c_phi.split_infra_pipeline()

# Assign BGs to Zones
c_phi.assign_bg2zones()

# Aand export it
c_phi.export_final_dataset()

In [7]:
c_phi.final_dataset.groupby(zone_same)

,activity_id,O_bg_fips,D_bg_fips,primary_mode,O_bg_lng,O_bg_lat,D_bg_lat,D_bg_lng,dist_m,zoneID_o,zoneID_d,zone_same
0,412690593163544293,421010002001,421010001011,private_auto,-75.1561,39.9554,39.9518,-75.1502,827.194860,14,14,True
1,14086516277722858880,421010002001,421010001012,walking,-75.1561,39.9554,39.9500,-75.1500,1136.624059,14,14,True
2,7103169478301938772,421010002001,421010001014,walking,-75.1561,39.9554,39.9503,-75.1456,1245.092542,14,14,True
3,4176995046867281827,421010002001,421010001014,private_auto,-75.1561,39.9554,39.9503,-75.1456,1307.280143,14,14,True
4,1413000380345929783,421010002001,421010001023,private_auto,-75.1561,39.9554,39.9533,-75.1440,1919.985998,14,14,True
...,...,...,...,...,...,...,...,...,...,...,...,...
4373963,14801556671112186703,421019893002,421019893002,commercial,-75.1181,40.0073,40.0073,-75.1181,359.679873,9,9,True
4373964,15809374473015086058,421019893002,421019893002,other_travel_mode,-75.1181,40.0073,40.0073,-75.1181,0.000000,9,9,True
4373965,7090153639574779221,421019893002,421019893002,commercial,-75.1181,40.0073,40.0073,-75.1181,0.000000,9,9,True
4373966,9367569926862519326,421019893002,421019893002,walking,-75.1181,40.0073,40.0073,-75.1181,148.905764,9,9,True
4373967,3260374487004730485,421019893002,421019893002,other_travel_mode,-75.1181,40.0073,40.0073,-75.1181,0.000000,9,9,True

In [26]:
from city import *
# Create City
c_phi2 = City('Philadelphia',GEO_DEFINITIONS['phi'], '../data/replica_exports/replica-phi_sat_spring_2024-01_14_25-trips_dataset.csv')
c_sfba2 = City('SF Bay Area',GEO_DEFINITIONS['sfba'], '../data/replica_exports/replica-ca_sat_spring_2024-01_14_25-trips_dataset.csv')
print('\tsfba done')
c_nyc2 = City('New York City',GEO_DEFINITIONS['nyc'], '../data/replica_exports/replica-ny_sat_spring_2024-01_14_25-trips_dataset.csv')
print('\tnyc done')
c_chi2 = City('Chicago',GEO_DEFINITIONS['chi'], '../data/replica_exports/replica-chi_sat_spring_2024-01_14_25-trips_dataset.csv')
print('\tchi done')

# c_phi2 = City('Philadelphia',GEO_DEFINITIONS['phi'])
# c_sfba2 = City('SF Bay Area',GEO_DEFINITIONS['sfba'])
# c_nyc2 = City('New York City',GEO_DEFINITIONS['nyc'])
# c_chi2 = City('Chicago',GEO_DEFINITIONS['chi'])

# c_phi2.blockgroup_centroids = c_phi.trip_data
# c_sfba2.blockgroup_centroids = c_sfba.trip_data
# c_nyc2.blockgroup_centroids = c_nyc.trip_data
# c_chi2.blockgroup_centroids = c_chi.trip_data

# c_phi2.blockgroup_centroids = c_phi2.get_blockgroups(c_phi2.trip_data)
# c_sfba2.blockgroup_centroids = c_sfba2.get_blockgroups(c_sfba2.trip_data)
# c_nyc2.blockgroup_centroids = c_nyc2.get_blockgroups(c_nyc2.trip_data)
# c_chi2.blockgroup_centroids = c_chi2.get_blockgroups(c_chi2.trip_data)

# Add Infrastructure
c_phi2.load_infrastructure(INFRA_TYPES_2)
print('Loading Infra_types')
c_sfba2.load_infrastructure(INFRA_TYPES_2)
print('\tsfba done')
c_nyc2.load_infrastructure(INFRA_TYPES_2)
print('\tsfba done')
c_chi2.load_infrastructure(INFRA_TYPES_2)
print('\tchi done')

# Split
print('Splitting into Zones')
c_phi2.split_infra_pipeline()
c_sfba2.split_infra_pipeline()
c_nyc2.split_infra_pipeline()
c_chi2.split_infra_pipeline()

# Assign BGs to Zones
print('Assigning BGs')
c_phi2.assign_bg2zones()
c_sfba2.assign_bg2zones()
c_nyc2.assign_bg2zones()
c_chi2.assign_bg2zones()

print('export_final_dataset')
# Assign BGs to Zones
c_phi2.export_final_dataset()
c_sfba2.export_final_dataset()
c_nyc2.export_final_dataset()
c_chi2.export_final_dataset()

	sfba done
	nyc done
	chi done
Loading Infra_types
	sfba done
	sfba done
	chi done
Splitting into Zones
Assigning BGs
export_final_dataset

In [29]:
c_phi2.final_dataset.to_csv('../data/exports/phi2_zones_raw_trips.csv')
c_chi2.final_dataset.to_csv('../data/exports/chi2_zones_raw_trips.csv')
c_nyc2.final_dataset.to_csv('../data/exports/nyc2_zones_raw_trips.csv')
c_sfba2.final_dataset.to_csv('../data/exports/sfba2_zones_raw_trips.csv')

In [20]:
c_phi.proj

'EPSG:3857'

In [3]:
# Chicago
c_chi = City('Chicago',GEO_DEFINITIONS['chi'], '../data/replica_exports/replica-chi_sat_spring_2024-01_14_25-trips_dataset.csv')
c_chi.load_infrastructure(INFRA_TYPES)
c_chi.split_infra_pipeline()
c_chi.assign_bg2zones()
c_chi.export_final_dataset()
c_chi.final_dataset.to_csv('../data/exports/phi_zones_raw_trips.csv')

KeyboardInterrupt:

In [10]:
#c_phi.final_dataset[['activity_id','O_bg_fips', 'D_bg_fips', 'primary_mode','dist_m', 'zoneID_o', 'zoneID_d', 'zone_same']].to_csv('../data/exports/phi_zones_raw_trips.csv')
c_chi.final_dataset[['activity_id','O_bg_fips', 'D_bg_fips', 'primary_mode','dist_m', 'zoneID_o', 'zoneID_d', 'zone_same']]#.to_csv('../data/exports/chi_zones_raw_trips.csv')

,activity_id,O_bg_fips,D_bg_fips,primary_mode,dist_m,zoneID_o,zoneID_d,zone_same
0,8850335778169708312,170310101001,170310102021,walking,965.122514,1073,1073,True
1,10442573869537517975,170310101001,170310103001,private_auto,1158.021160,1073,1073,True
2,7295663170821018978,170310101001,170310105032,private_auto,2402.321468,1073,1073,True
3,9270753833368418998,170310101001,170310407004,private_auto,8596.837255,1073,1073,True
4,4023870781627070128,170310101001,170311612001,private_auto,16702.825858,1073,190,False
...,...,...,...,...,...,...,...,...
15553478,2328045440849413224,170319801001,170319801001,commercial,1226.003462,198,198,True
15553479,11765288775074567821,170319801001,170319801001,walking,0.000000,198,198,True
15553480,16097793491369776226,170319801001,170319801001,commercial,1417.809630,198,198,True
15553481,14422232100915129267,170319801001,170319801001,other_travel_mode,0.000000,198,198,True
15553482,2876510789626390709,170319801001,170319801001,walking,536.182932,198,198,True

In [11]:
# NYC
print('1')
c_nyc = City('New York',GEO_DEFINITIONS['nyc'], '../data/replica_exports/replica-ny_sat_spring_2024-01_14_25-trips_dataset.csv')
print('2')
c_nyc.load_infrastructure(INFRA_TYPES)
print('3')
c_nyc.split_infra_pipeline()
print('4')
c_nyc.assign_bg2zones()
print('5')
c_nyc.export_final_dataset()
print('6')
c_nyc.final_dataset[['activity_id','O_bg_fips', 'D_bg_fips', 'primary_mode','dist_m', 'zoneID_o', 'zoneID_d', 'zone_same']].to_csv('../data/exports/nyc_zones_raw_trips.csv')
print('Done!')

1
2
3

/Users/jon/anaconda3/envs/cyp204d/lib/python3.9/site-packages/geopandas/geodataframe.py:1819: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super().__setitem__(key, value)

4
5
6
Done!

In [12]:
# SFBA
print('1')
c_sfba = City('SF Bay Area',GEO_DEFINITIONS['sfba'], '../data/replica_exports/replica-ca_sat_spring_2024-01_14_25-trips_dataset.csv')
print('2')
c_sfba.load_infrastructure(INFRA_TYPES)
print('3')
c_sfba.split_infra_pipeline()
print('4')
c_sfba.assign_bg2zones()
print('5')
c_sfba.export_final_dataset()
print('6')
c_sfba.final_dataset[['activity_id','O_bg_fips', 'D_bg_fips', 'primary_mode','dist_m', 'zoneID_o', 'zoneID_d', 'zone_same']].to_csv('../data/exports/sfba_zones_raw_trips.csv')
print('Done!')

1
2
3

/Users/jon/anaconda3/envs/cyp204d/lib/python3.9/site-packages/geopandas/geodataframe.py:1819: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  super().__setitem__(key, value)

4
5
6
Done!